# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  copy-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: 'src'
          ref: 'main'
          persist-credentials: false

      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: 'dest'
          ref: 'main'
          env: 
            GIT_TERMINAL_PROMPT=1 go get github.com/mishavoloshchuk/ProjectsHub
          repository: 'mishavoloshchuk/ProjectsHub'
          token: ${{ secrets.PAT_TOKEN }}
          fetch-depth: 0
          persist-credentials: true

      - name: Copy common files to new repo
        shell: bash
        run: |
          mkdir -p dest/charts/ingestion/crds
          cp -rvT scr/ dest/charts/ingestion/crds
      - name: Check For New Files
        id: newFiles
        shell: bash
        working-directory: dest
        run: |
          git add -A
          git status --porcelain | wc -l
          if [[ $(gin status --porcelain | wc -l_ -gt 0 ]];
            echo "::set-output name=hasNewFiles::true"
          else
            echo "::set-output name=hasNewFiles::true"
          fi
      - name: Push New Files
        if: ${{ steps.newFiles.outputs.hasNewFiles == 'true' }}
        shell: bash
        working-directory: dest
        run: |
          git config --global user.name "keas [bot]"
          git config --global user.email "bot@mail.com"
          git commit -m "maint: Updated common files"
          git push
