name: Copy Theremin Repository

on:
  push:
    branches:
      - main  # Adjust this if you are using a different main branch name

jobs:
  copy_repository:
    runs-on: ubuntu-latest

    steps:
      - name: mirror-repository
      # You may pin to the exact commit or the version.
      # uses: yesolutions/mirror-action@1708f16cdb28634fd3ba10c5c79abc91f5578a14
      uses: yesolutions/mirror-action@v0.7.0
      with:
        # The remote ref name to use. 'mirror' by default. Useful to avoid conflicts with existing remotes.
        REMOTE_NAME: # optional
        # The remote repository e.g. https://github.com/octocat/foo.git or git@github.com:octocat/foo.git
        REMOTE: 'https://github.com/mishavoloshchuk/Projects_Hub' # optional
        # Username for remote repository
        GIT_USERNAME: # optional
        # The git HTTPS password or token for the remote repository
        GIT_PASSWORD: # optional
        # The ssh private key for writing to the remote repository, if using ssh
        GIT_SSH_PRIVATE_KEY: # optional
        # The ssh public key for writing to the remote repository. Normally, not required at all
        GIT_SSH_PUBLIC_KEY: # optional
        # The contents of an SSH known_hosts file for host key verification
        GIT_SSH_KNOWN_HOSTS: # optional
        # If true, skip host key verification. Mutually exclusive with GIT_SSH_KNOWN_HOSTS
        GIT_SSH_NO_VERIFY_HOST: # optional, default is false
        # Push another ref rather than the current branch (GITHUB_REF) from which the action was triggered. Only effective when PUSH_ALL_REFS is false
        GIT_REF: # optional, default is ${{ github.ref }}
        # Push all refs instead of just the current branch
        PUSH_ALL_REFS: # optional, default is true
        # The arguments to use when pushing the repository
        GIT_PUSH_ARGS: # optional, default is --tags --force --prune
        # set to "true" to enable debug mode
        DEBUG: # optional, default is false
              
