# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  copy-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: 'src'
          ref: 'main'
          persist-credentials: false
          
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v3
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: 'git@github.com:mishavoloshchuk/ProjectsHub'

      - name: Config
        run: |
          git config --global url."git@github.com:".insteadOf "https://github.com/"

      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: 'dest'
          ref: 'main'
          repository: 'mishavoloshchuk/ProjectsHub'
          ssh-key: ${{ secrets.SSH_KEY }}
          token: ${{ secrets.SSH_KEY }}
          fetch-depth: 0
          persist-credentials: true

      - name: Copy common files to new repo
        shell: bash
        run: |
          mkdir -p dest/charts/ingestion/crds
          cp -rvT scr/ dest/charts/ingestion/crds
      - name: Check For New Files
        id: newFiles
        shell: bash
        working-directory: dest
        run: |
          git add -A
          git status --porcelain | wc -l
          if [[ $(gin status --porcelain | wc -l_ -gt 0 ]];
            echo "::set-output name=hasNewFiles::true"
          else
            echo "::set-output name=hasNewFiles::true"
          fi
      - name: Push New Files
        if: ${{ steps.newFiles.outputs.hasNewFiles == 'true' }}
        shell: bash
        working-directory: dest
        run: |
          git config --global user.name "keas [bot]"
          git config --global user.email "bot@mail.com"
          git commit -m "maint: Updated common files"
          git push
