name: Copy Theremin Repository

on:
  push:
    branches:
      - main

jobs:
  copy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create destination directory
        run: mkdir -p Projects_Hub/projects/Theremin

      - name: Copy files
        run: rsync -av --exclude=Projects_Hub/ * Projects_Hub/projects/Theremin/

      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add -A
          git commit -m "Copy Theremin repository"
          git push
