name: Copy Theremin repository to Projects_Hub

on:
  push:
    branches:
      - main

jobs:
  copy_repository:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create destination folder
      run: mkdir -p Projects_Hub/projects/Theremin

    - name: Copy repository to destination folder
      run: cp -a . Projects_Hub/projects/Theremin

    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add -A
        git commit -m "Copy Theremin repository to Projects_Hub"
        git push
