name: Copy Theremin Repository to Projects_Hub

on:
  push:
    branches:
      - main # Change this to the default branch of your repository

jobs:
  copy_repository:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create Projects_Hub directory
      run: mkdir -p Projects_Hub/projects/Theremin

    - name: Copy Theremin repository
      run: cp -r * Projects_Hub/projects/Theremin

    - name: Commit and push changes
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add -A
        git commit -m "Copy Theremin repository to Projects_Hub"
        git push
